In [1]:
#Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [2]:
import numpy as np

In [3]:
arr1 = np.random.randint(10, 100, 50)

In [4]:
arr1

array([16, 92, 30, 31, 76, 29, 72, 55, 21, 79, 70, 37, 51, 37, 68, 96, 41,
       50, 96, 47, 45, 65, 36, 55, 55, 66, 15, 30, 49, 80, 49, 48, 79, 67,
       26, 29, 56, 29, 89, 20, 28, 20, 48, 90, 55, 23, 63, 60, 98, 31])

In [5]:
multiplos_5 = arr1[::5]

In [6]:
multiplos_5

array([16, 29, 70, 96, 45, 66, 49, 29, 28, 23])

In [7]:
# Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [8]:
arr2 = np.random.randint(1, 21, 30)

In [9]:
arr2

array([16,  1,  4, 20, 19,  9, 10,  7, 12, 19,  3, 18,  7, 20,  5,  4,  2,
        3, 19,  5, 19, 13,  4, 15,  1, 18,  4, 16, 10,  8])

In [10]:
impares = arr2[::2]

In [11]:
impares

array([16,  4, 19, 10, 12,  3,  7,  5,  2, 19, 19,  4,  1,  4, 10])

In [12]:

#Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 
#Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [13]:
arr3 = np.random.randint(5, 25, (4,6)) + np.random.rand(4,6) 

In [14]:
arr3

array([[ 9.67922052, 15.38665267, 16.17931   , 15.29753271, 12.62140097,
        22.38344269],
       [ 5.56770085,  8.35341592, 18.876747  , 17.25217005, 16.24891286,
        16.14578522],
       [ 8.3371777 , 20.74071998, 13.12204343,  9.93581038,  5.90818548,
        16.12536564],
       [12.50784071, 12.09858544, 14.03119664,  7.36877273,  8.37968525,
        11.9351189 ]])

In [15]:
arr3 = np.round (arr3, 2)

In [16]:
arr3

array([[ 9.68, 15.39, 16.18, 15.3 , 12.62, 22.38],
       [ 5.57,  8.35, 18.88, 17.25, 16.25, 16.15],
       [ 8.34, 20.74, 13.12,  9.94,  5.91, 16.13],
       [12.51, 12.1 , 14.03,  7.37,  8.38, 11.94]])

In [17]:
ultima_fila = arr3[-1]

In [18]:
ultima_fila

array([12.51, 12.1 , 14.03,  7.37,  8.38, 11.94])

In [19]:
arr3_1 = np.random.rand(4,6) # prueba que hemos hecho con valores 0 y 1

In [20]:
arr3_1

array([[0.26602897, 0.6740286 , 0.63263934, 0.42500999, 0.05672327,
        0.60928038],
       [0.64387539, 0.96774004, 0.5715995 , 0.8958755 , 0.30014337,
        0.07717959],
       [0.51173835, 0.33535065, 0.62271932, 0.49765181, 0.75791516,
        0.25791405],
       [0.88772349, 0.45657448, 0.24395068, 0.92892373, 0.43567179,
        0.23598413]])

In [21]:
#Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [22]:
arr3D = np.random.rand(2, 3, 5)

In [23]:
arr3D

array([[[0.53807695, 0.02506216, 0.12795066, 0.54076891, 0.32446688],
        [0.92046436, 0.5815091 , 0.88824797, 0.98625934, 0.73754701],
        [0.96903424, 0.98453459, 0.30474408, 0.42767441, 0.84508859]],

       [[0.85844875, 0.51584446, 0.5493143 , 0.04555709, 0.4709259 ],
        [0.73219006, 0.22593697, 0.95211206, 0.05497212, 0.00884832],
        [0.59223895, 0.91624711, 0.42640005, 0.2981674 , 0.86579352]]])

In [24]:
arr3D = np.round(arr3D, 1)

In [25]:
arr3D

array([[[0.5, 0. , 0.1, 0.5, 0.3],
        [0.9, 0.6, 0.9, 1. , 0.7],
        [1. , 1. , 0.3, 0.4, 0.8]],

       [[0.9, 0.5, 0.5, 0. , 0.5],
        [0.7, 0.2, 1. , 0.1, 0. ],
        [0.6, 0.9, 0.4, 0.3, 0.9]]])

In [26]:
#Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 
#Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los 
#valores del primer array bajo las siguientes condiciones:

#Si el valor del array es igual que la media, se reemplaza por "A".

#Si el valor del array es mayor que la media, se reemplaza por "B".

#Si el valor del array es menor que la media, se reemplaza por "C".

#Si el valor es igual que el máximo, se reemplaza por "D".

#Si el valor es igual que el mínimo, se reemplaza por "E".

array_vacio = np.empty((filas, columnas), dtype=tipo_de_dato)        #sintaxis array vacio

In [27]:
media = np.mean(arr3D)
maximo = np.max(arr3D)
minimo = np.min(arr3D)

In [28]:
# Crear un array vacío con la misma forma y dimensiones que arr3D
arr_vacio = np.empty_like(arr3D, dtype=object)   
#para crear un array vacío con la misma forma y dimensiones que arr3D. El tipo object es necesario para poder almacenar letras como "A", "B", etc.

np.where(condición, valor_si_verdadera, valor_si_falsa) 
np.where para asignación de letras según las condiciones, reemplazando los valores del array vacío

In [29]:
 # Reemplazar por "A" si es igual a la media
arr_vacio = np.where(arr3D == media, "A", arr_vacio) 

In [30]:
# Reemplazar por "B" si es mayor que la media
arr_vacio = np.where(arr3D > media, "B", arr_vacio) 

In [31]:
# Reemplazar por "C" si es menor que la media
arr_vacio = np.where(arr3D < media, "C", arr_vacio)   

In [32]:
# Reemplazar por "D" si es igual al máximo
arr_vacio = np.where(arr3D == maximo, "D", arr_vacio) 

In [33]:
# Reemplazar por "E" si es igual al mínimo
arr_vacio = np.where(arr3D == minimo, "E", arr_vacio) 

In [34]:
arr_vacio

array([[['C', 'E', 'C', 'C', 'C'],
        ['B', 'B', 'B', 'D', 'B'],
        ['D', 'D', 'C', 'C', 'B']],

       [['B', 'C', 'C', 'E', 'C'],
        ['B', 'C', 'D', 'C', 'E'],
        ['B', 'B', 'C', 'C', 'B']]], dtype=object)