## Ejercicios

### ¿Qué diferencia hay entre una Serie y un DataFrame?

### Es el turno de los DataFrames

1. Crea un array de dos dimensiones con 4 filas y 3 columnas.


In [52]:
import numpy as np
import pandas as pd

In [53]:
array_pair = np.random.rand(4,3)
print (array_pair)

[[0.12064335 0.41318615 0.15610623]
 [0.1801212  0.03598125 0.63228453]
 [0.61812193 0.25313795 0.17442003]
 [0.56962695 0.17556358 0.10532734]]


In [54]:
df_paises = pd.DataFrame (array_pair)
print(df_paises)

          0         1         2
0  0.120643  0.413186  0.156106
1  0.180121  0.035981  0.632285
2  0.618122  0.253138  0.174420
3  0.569627  0.175564  0.105327


2. Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [55]:
df_paises = pd.DataFrame  (array_pair, columns = ['Francia', 'España', 'Italia'])
print(df_paises)

    Francia    España    Italia
0  0.120643  0.413186  0.156106
1  0.180121  0.035981  0.632285
2  0.618122  0.253138  0.174420
3  0.569627  0.175564  0.105327



## Descarga el archivo "medallas" y carga el DataFrame.

In [56]:
medallas = pd.read_csv ('archivos/medallas.csv')
print(medallas)

   Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235


In [57]:
type(medallas)

pandas.core.frame.DataFrame

In [58]:
df_medallas = pd.DataFrame (medallas.set_index('País'))

In [59]:
print(df_medallas)

                 Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235


In [60]:
type(df_medallas)

pandas.core.frame.DataFrame

In [61]:
df_medallas = df_medallas.drop(columns=["Unnamed: 0"])

In [62]:
print(df_medallas)

                  Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235


Usando el loc extrae todas las columnas de la fila de Tailandia.

In [67]:
valores = df_medallas.loc['Tailandia']
print(f'Los datos del país Tailandia son:\n{valores}')

Los datos del país Tailandia son:
Oro       132
Plata     175
Bronce    278
Name: Tailandia, dtype: int64


 Usando el loc extrae todas las columnas de China e Irán.
 
 Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

In [ ]:
df_medallas.loc[['China','Irán']]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

Usando el iloc extrae la información de la India. Devolved todas las columnas.

In [ ]:
df_medallas

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

In [ ]:
print(f'Los datos de la India son \n{df_medallas.iloc[5]}')

Los datos de la India son 
Oro       154
Plata     202
Bronce    315
Name: India, dtype: int64


Usando el iloc extrae todas las columnas de los países que estén en posición impar. 

La primera que nos tendría que salir es Japón y la última Corea del Norte.

In [ ]:
df_medallas.iloc [1::2]

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

    Utilizando el código del ejercicio anterior, selecciona unicamente la columna "Plata".

In [ ]:
df_medallas.iloc[1::2,1:2]

Plata
País                  
Japón             1037
Irán               181
India              202
Indonesia          131
Corea del Norte    120

Contesta a las siguientes preguntas:

            ¿Qué país consiguió más de 200 medallas de oro?

In [ ]:
df_medallas_oro = df_medallas[df_medallas['Oro'] > 200]
print (f'Los países que han ganadao más de 200 medallas de oro han sido: \n{df_medallas_oro}')

Los países que han ganadao más de 200 medallas de oro han sido: 
                Oro  Plata  Bronce
País                              
China          1473    994     720
Japón          1032   1037     985
Corea del Sur   745    663     827


In [ ]:
df_medallas_oro['Oro']

País
China            1473
Japón            1032
Corea del Sur     745
Name: Oro, dtype: int64

 ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

In [ ]:
df_medallas_filtro = df_medallas[(df_medallas['Oro'] > 200)&(df_medallas['Plata'] > 1000)]
print(df_medallas_filtro)

        Oro  Plata  Bronce
País                      
Japón  1032   1037     985


            ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

In [ ]:
df_medallas_filtro2 = df_medallas[(df_medallas['Oro'] > 200)|(df_medallas['Bronce'] > 700)]
print(df_medallas_filtro2)

                Oro  Plata  Bronce
País                              
China          1473    994     720
Japón          1032   1037     985
Corea del Sur   745    663     827


        Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [ ]:
df_medallas

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

In [ ]:
df_medallas['total'] = df_medallas['Oro'] + df_medallas['Plata'] + df_medallas['Bronce']

In [ ]:
df_medallas

Oro  Plata  Bronce  total
País                                       
China            1473    994     720   3187
Japón            1032   1037     985   3054
Corea del Sur     745    663     827   2235
Irán              179    181     197    557
Kazajistán        155    158     224    537
India             154    202     315    671
Tailandia         132    175     278    585
Indonesia         112    131     240    483
China Taipéi       99    144     276    519
Corea del Norte    91    120     235    446

Momento de trabajar con Series. Contesta a las siguientes preguntas:

    Crea dos listas:

        Una que se llame "valores" que tenga 7 números aleatorios.

        Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

    A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [ ]:
valores = [3,67,89,1,5,63,14]
indices = ['lunes','martes', 'miércoles','jueves','viernes','sábado','domingo']

In [ ]:
serie_pair = pd.Series(valores, index = indices)
print(serie_pair)

lunes         3
martes       67
miércoles    89
jueves        1
viernes       5
sábado       63
domingo      14
dtype: int64


A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más información sobre este método aquí.

    Crea una Serie con el diccionario creado en el punto anterior.

In [ ]:
diccionario = {}

for i in range(len(indices)):
    diccionario[indices[i]]=valores[i]

print(diccionario)

{'lunes': 3, 'martes': 67, 'miércoles': 89, 'jueves': 1, 'viernes': 5, 'sábado': 63, 'domingo': 14}


In [ ]:
serie_diccionario = pd.Series(diccionario)
print(serie_diccionario)

lunes         3
martes       67
miércoles    89
jueves        1
viernes       5
sábado       63
domingo      14
dtype: int64


      ¿Qué forma tiene esta última Serie?

    ¿Qué tipo de datos tiene?

    ¿Qué tamaño tiene?

    ¿Cuáles son los índices de la Serie?

    ¿Y los values?


In [ ]:
serie_diccionario.shape

(7,)

In [ ]:
serie_diccionario.dtypes

dtype('int64')

In [ ]:
serie_diccionario.size

7

In [ ]:
serie_diccionario.index

Index(['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado',
       'domingo'],
      dtype='object')

In [ ]:
serie_diccionario.values

array([ 3, 67, 89,  1,  5, 63, 14])

 Extrae el valor para el índice "lunes"

In [ ]:
serie_diccionario['lunes']

3

 Extrae el valor para el índice "lunes", "martes" y "miércoles".

In [ ]:
serie_diccionario.loc [['lunes','martes','miércoles']]

lunes         3
martes       67
miércoles    89
dtype: int64

In [ ]:
valores= serie_diccionario.loc [['lunes','martes','miércoles']]
print(valores)

lunes         3
martes       67
miércoles    89
dtype: int64


    Extrae el valor para el índice "lunes" y "domingo".

In [69]:
serie_diccionario.iloc[0:7:6]

lunes       3
domingo    14
dtype: int64